---
abstract: 'Dynamic instrumentation like DTrace, using aspects'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 6.58
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120620'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: dip
no_index:
  directory:
    - t
    - inc
requires:
  Aspect: 1.02
  Carp: 0
  Data::Dumper: 0
  File::Slurp: 0
  Getopt::Long: 0
  Term::ANSIColor: 0
  Time::HiRes: 0
  autodie: 0
version: 1.17
