---
abstract: 'Dynamic instrumentation like DTrace, using aspects'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: dip
provides:
  dip:
    file: lib/dip.pm
    version: 1.111060
requires:
  Aspect: 0
  Carp: 0
  Data::Dumper: 0
  Getopt::Long: 0
  Time::HiRes: 0
  autodie: 0
  perl: 5.010
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=dip
  homepage: http://search.cpan.org/dist/dip/
  repository: git://github.com/hanekomu/dip.git
version: 1.111060
